// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxyvkcvplgtqorcglzph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4eXZrY3ZwbGd0cW9yY2dsenBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzkwMTYsImV4cCI6MjA2Nzg1NTAxNn0.xS0kqKbxhqbuO0rtzO79vgUSvwsgpmligvrIdTzAAz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});